// src/app/App.tsx
import { useEffect } from 'react';
import { ThemeToggle } from './components/ThemeToggle';
import { Hero } from './components/Hero';
import { About } from './components/About';
import { Projects } from './components/Projects';
import { Skills } from './components/Skills';
import { Contact } from './components/Contact';
import { Footer } from './components/Footer';

export default function App() {
  useEffect(() => {
    const handleSmoothScroll = (e: MouseEvent) => {
      const target = e.target as HTMLAnchorElement;
      if (target.tagName === 'A' && target.hash) {
        const href = target.getAttribute('href');
        if (href?.startsWith('#')) {
          e.preventDefault();
          const element = document.querySelector(href);
          if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'start' });
          }
        }
      }
    };

    document.addEventListener('click', handleSmoothScroll);
    return () => document.removeEventListener('click', handleSmoothScroll);
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      <ThemeToggle />

      <main>
        <Hero />
        <About />
        <Projects />
        <Skills />
        <Contact />
      </main>

      <Footer />
    </div>
  );
}

// src/App.vue
<template>
	<main class="app">
		<Navbar v-on:change-menu="changeMenu" />
		<main class="mt-16">
			<Landing ref="home" />
			<About />
			<Uiux />
			<Frontend />
			<Contact />
			<Footer	/>
		</main>
	</main>
</template>

<script setup>

import { ref } from 'vue'
import Landing from '@/components/Landing.vue'
import About from '@/components/About.vue'
import Navbar from '@/components/Navbar.vue'
import Uiux from '@/components/Uiux.vue'
import Frontend from '@/components/Frontend.vue'
import Contact from '@/components/Contact.vue'
import Footer from '@/components/Footer.vue'

const home = ref(null)

const changeMenu = payload => {
	getEl(payload).scrollIntoView({
		behavior: 'smooth',
		block: 'start',
		inline: 'nearest'
	})
}

const getEl = id => document.querySelector(id)
</script>

<style scoped>
.app {
	@apply w-full;
}
</style>
